const mapElement = document.querySelector("#map"), selector = document.querySelector("#cyclone"), timeSelector = document.querySelector("#risk-time"), metadata = document.querySelector("#metadata"), controls = document.querySelector("#layer-controls"), riskDetail = document.querySelector("#risk-detail"), assistantForm = document.querySelector("#assistant-form"), assistantQuestion = document.querySelector("#assistant-question"), assistantResponse = document.querySelector("#assistant-response"), scenarioForm = document.querySelector("#scenario-form"), scenarioSummary = document.querySelector("#scenario-summary"), scenarioComparison = document.querySelector("#scenario-comparison");
const layerColors = { rainfall: "#2563eb", elevation: "#15803d", population: "#9333ea" }, bandColors = { low: "#22c55e", medium: "#f59e0b", high: "#dc2626" };
let track, locations, forecasts, risk, activeLayers = new Set(), showRisk = true;

function riskFor(locationId) { return risk.features.find(feature => feature.properties.location_id === locationId); }
function coordinates() { return [...track.features.filter(feature => feature.geometry.type === "Point").map(feature => feature.geometry.coordinates), ...forecasts.map(point => [point.longitude, point.latitude]), ...locations.features.flatMap(feature => feature.geometry.coordinates[0])]; }
function polygon(location, x, y) { return location.geometry.coordinates[0].map(point => `${x(point[0])},${y(point[1])}`).join(" "); }
function renderFallback() {
  const values = coordinates(), width = 900, height = 520, padding = 45, longitudes = values.map(point => point[0]), latitudes = values.map(point => point[1]), minLon = Math.min(...longitudes), maxLon = Math.max(...longitudes), minLat = Math.min(...latitudes), maxLat = Math.max(...latitudes);
  const x = value => padding + ((value - minLon) / (maxLon - minLon || 1)) * (width - 2 * padding), y = value => height - (padding + ((value - minLat) / (maxLat - minLat || 1)) * (height - 2 * padding));
  const observed = track.features.filter(feature => feature.geometry.type === "Point"), observedPath = observed.map(point => `${x(point.geometry.coordinates[0])},${y(point.geometry.coordinates[1])}`).join(" "), forecastPath = [observed.at(-1).geometry.coordinates, ...forecasts.map(point => [point.longitude, point.latitude])].map(point => `${x(point[0])},${y(point[1])}`).join(" ");
  const context = locations.features.flatMap(location => [...activeLayers].map(layerId => `<polygon points="${polygon(location, x, y)}" fill="${layerColors[layerId]}" fill-opacity="0.12" stroke="${layerColors[layerId]}"/>`)).join(""), heatmap = showRisk ? locations.features.map(location => { const score = riskFor(location.properties.location_id).properties; return `<polygon data-location="${location.properties.location_id}" points="${polygon(location, x, y)}" fill="${bandColors[score.band]}" fill-opacity="0.38" stroke="${bandColors[score.band]}" stroke-width="3"><title>${location.properties.name}: ${score.risk_score}/100 (${score.band})</title></polygon>`; }).join("") : "";
  mapElement.innerHTML = `<svg viewBox="0 0 ${width} ${height}" width="100%" height="100%"><rect width="100%" height="100%" fill="#edf5fb"/>${context}${heatmap}<polyline points="${observedPath}" fill="none" stroke="#b62727" stroke-width="4"/><polyline points="${forecastPath}" fill="none" stroke="#7e22ce" stroke-width="3" stroke-dasharray="10 6"/>${observed.map(point => `<circle cx="${x(point.geometry.coordinates[0])}" cy="${y(point.geometry.coordinates[1])}" r="6" fill="#b62727"/>`).join("")}${forecasts.map(point => `<circle cx="${x(point.longitude)}" cy="${y(point.latitude)}" r="6" fill="#7e22ce"/>`).join("")}<text x="20" y="30" fill="#48576a">Red solid: observed. Purple dashed: forecast. Offline coordinate-map fallback.</text></svg>`;
  mapElement.querySelectorAll("[data-location]").forEach(element => element.addEventListener("click", () => showRiskDetail(element.dataset.location)));
}
function renderGoogleMap() {
  const observed = track.features.filter(feature => feature.geometry.type === "Point").map(feature => ({ lng: feature.geometry.coordinates[0], lat: feature.geometry.coordinates[1] })), forecastPath = [...observed.slice(-1), ...forecasts.map(point => ({ lng: point.longitude, lat: point.latitude }))], map = new google.maps.Map(mapElement, { center: observed.at(-1), zoom: 5, mapTypeControl: false });
  new google.maps.Polyline({ path: observed, map, strokeColor: "#b62727", strokeWeight: 4 }); new google.maps.Polyline({ path: forecastPath, map, strokeColor: "#7e22ce", strokeWeight: 3, icons: [{ icon: { path: "M 0,-1 0,1", strokeOpacity: 1, scale: 4 }, offset: "0", repeat: "20px" }] });
  locations.features.forEach(location => { const score = riskFor(location.properties.location_id).properties, paths = location.geometry.coordinates[0].map(([lng, lat]) => ({ lng, lat })); [...activeLayers].forEach(layerId => new google.maps.Polygon({ paths, map, fillColor: layerColors[layerId], fillOpacity: .12, strokeColor: layerColors[layerId] })); if (showRisk) { const shape = new google.maps.Polygon({ paths, map, fillColor: bandColors[score.band], fillOpacity: .38, strokeColor: bandColors[score.band], strokeWeight: 3 }); shape.addListener("click", () => showRiskDetail(location.properties.location_id)); } });
}
function renderMap() { window.google?.maps ? renderGoogleMap() : renderFallback(); }
function addControl(text, checked, onChange) { const label = document.createElement("label"), input = document.createElement("input"); input.type = "checkbox"; input.checked = checked; input.addEventListener("change", () => onChange(input.checked)); label.append(input, ` ${text}`); controls.append(label); }
function renderControls(layers) { controls.replaceChildren(); addControl("Baseline risk heatmap", showRisk, checked => { showRisk = checked; renderMap(); }); layers.forEach(layer => { activeLayers.add(layer.layer_id); addControl(`${layer.name} (${layer.unit})`, true, checked => { checked ? activeLayers.add(layer.layer_id) : activeLayers.delete(layer.layer_id); renderMap(); }); const detail = document.createElement("div"); detail.className = "metadata"; detail.textContent = `${layer.source}; ${layer.observed_at}; ${layer.resolution}`; controls.append(detail); }); }
async function loadRisk() { const validTime = timeSelector.value; risk = await fetch(`/cyclones/${encodeURIComponent(selector.value)}/risk?valid_time=${encodeURIComponent(validTime)}`).then(response => response.json()); renderMap(); }
async function showRiskDetail(locationId) { const score = await fetch(`/locations/${encodeURIComponent(locationId)}/risk?cyclone_id=${encodeURIComponent(selector.value)}&valid_time=${encodeURIComponent(timeSelector.value)}`).then(response => response.json()); riskDetail.replaceChildren(); const title = document.createElement("strong"), note = document.createElement("p"), list = document.createElement("ul"); title.textContent = `Risk score: ${score.risk_score}/100`; note.innerHTML = `<span class="band">${score.band}</span> ${score.source_type}; model ${score.model_version}; valid ${score.valid_time}.`; score.feature_contributions.forEach(item => { const row = document.createElement("li"); row.textContent = `${item.name}: ${item.raw_value}; normalised ${item.normalised_value}; weight ${item.weight}; ${item.score_points} score points`; list.append(row); }); riskDetail.append(title, note, list); }
function populateTimes() { timeSelector.replaceChildren(); const observedTime = track.features.filter(feature => feature.geometry.type === "Point").at(-1).properties.timestamp; const options = [{ value: observedTime, label: `Observed ${observedTime}` }, ...forecasts.map(point => ({ value: point.valid_time, label: `Forecast +${point.horizon_hours}h (${point.valid_time}; ±${point.uncertainty_km} km)` }))]; options.forEach(({ value, label }) => timeSelector.add(new Option(label, value))); }
async function selectCyclone() { const event = JSON.parse(selector.selectedOptions[0].dataset.event); [track, locations, forecasts] = await Promise.all([fetch(`/cyclones/${encodeURIComponent(event.cyclone_id)}/track`).then(response => response.json()), fetch(`/cyclones/${encodeURIComponent(event.cyclone_id)}/locations`).then(response => response.json()), fetch(`/cyclones/${encodeURIComponent(event.cyclone_id)}/forecast`).then(response => response.json()).then(payload => payload.points)]); metadata.textContent = `${event.name} | ${event.basin} | observed source: ${event.source} | ${event.observed_at}`; populateTimes(); activeLayers = new Set(); showRisk = true; renderControls(await fetch(`/cyclones/${encodeURIComponent(event.cyclone_id)}/layers`).then(response => response.json())); await loadRisk(); }
async function askAssistant(event) { event.preventDefault(); assistantResponse.textContent = "Retrieving grounded context…"; const response = await fetch("/query", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: assistantQuestion.value, cyclone_id: selector.value, valid_time: timeSelector.value }) }); const payload = await response.json(); if (!response.ok) { assistantResponse.textContent = payload.error; return; } const citations = payload.evidence.map(item => `${item.kind}: ${item.source} (${item.timestamp})`).join("; "); assistantResponse.textContent = `${payload.answer} Context: ${citations}. ${payload.uncertainty.join(" ")}`; }
function mapPoints(featureCollection) { return featureCollection.features.filter(feature => feature.geometry.type === "Point").map(feature => feature.geometry.coordinates); }
function scenarioSvg(trackData, scores, bounds, color) { const width = 420, height = 280, padding = 25, x = value => padding + ((value - bounds.minLon) / (bounds.maxLon - bounds.minLon || 1)) * (width - 2 * padding), y = value => height - (padding + ((value - bounds.minLat) / (bounds.maxLat - bounds.minLat || 1)) * (height - 2 * padding)); const scoresByLocation = Object.fromEntries(scores.map(score => [score.location_id, score])); const polygons = locations.features.map(location => { const score = scoresByLocation[location.properties.location_id]; return `<polygon points="${polygon(location, x, y)}" fill="${bandColors[score.band]}" fill-opacity=".38" stroke="${bandColors[score.band]}" stroke-width="2"><title>${location.properties.name}: ${score.risk_score}/100</title></polygon>`; }).join(""); const points = mapPoints(trackData), line = points.map(point => `${x(point[0])},${y(point[1])}`).join(" "); return `<svg class="scenario-map" viewBox="0 0 ${width} ${height}" width="100%"><rect width="100%" height="100%" fill="#edf5fb"/>${polygons}<polyline points="${line}" fill="none" stroke="${color}" stroke-width="4" stroke-dasharray="${color === '#7e22ce' ? '10 6' : '0'}"/>${points.map(point => `<circle cx="${x(point[0])}" cy="${y(point[1])}" r="4" fill="${color}"/>`).join("")}</svg>`; }
function renderScenarioComparison(result) { const all = [...mapPoints(result.baseline.track), ...mapPoints(result.simulation.track), ...locations.features.flatMap(location => location.geometry.coordinates[0])], longitudes = all.map(point => point[0]), latitudes = all.map(point => point[1]), bounds = { minLon: Math.min(...longitudes), maxLon: Math.max(...longitudes), minLat: Math.min(...latitudes), maxLat: Math.max(...latitudes) }; scenarioComparison.replaceChildren(); [["Baseline", result.baseline, "#b62727"], ["Simulation", result.simulation, "#7e22ce"]].forEach(([label, data, color]) => { const card = document.createElement("article"), heading = document.createElement("h3"); card.className = "scenario-card"; heading.textContent = label; card.append(heading); const map = document.createElement("div"); map.innerHTML = scenarioSvg(data.track, data.risk_scores, bounds, color); card.append(map); scenarioComparison.append(card); }); const changes = result.comparison.locations.map(row => `${row.name}: ${row.baseline_risk_score} → ${row.simulation_risk_score} (${row.risk_score_delta >= 0 ? "+" : ""}${row.risk_score_delta})`).join("; "); scenarioSummary.textContent = `SIMULATION ${result.scenario.scenario_id}. ${changes}. ${result.explanation.answer}`; }
async function runScenario(event) { event.preventDefault(); scenarioSummary.textContent = "Calculating deterministic simulation…"; const parameters = { track_shift_km: Number(document.querySelector("#track-shift").value), intensity_multiplier: Number(document.querySelector("#intensity-multiplier").value), rainfall_multiplier: Number(document.querySelector("#rainfall-multiplier").value) }; const response = await fetch("/scenario", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cyclone_id: selector.value, valid_time: timeSelector.value, parameters }) }); const result = await response.json(); if (!response.ok) { scenarioSummary.textContent = result.error; scenarioComparison.replaceChildren(); return; } renderScenarioComparison(result); }
async function start() { const config = await fetch("/map-config").then(response => response.json()); if (config.google_maps_api_key) await new Promise((resolve, reject) => { const script = document.createElement("script"); script.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(config.google_maps_api_key)}`; script.onload = resolve; script.onerror = reject; document.head.append(script); }); const cyclones = await fetch("/cyclones").then(response => response.json()); cyclones.forEach(event => { const option = new Option(event.name, event.cyclone_id); option.dataset.event = JSON.stringify(event); selector.add(option); }); selector.addEventListener("change", selectCyclone); timeSelector.addEventListener("change", loadRisk); assistantForm.addEventListener("submit", askAssistant); scenarioForm.addEventListener("submit", runScenario); await selectCyclone(); }
start().catch(error => { mapElement.textContent = `Unable to load cyclone forecast data: ${error.message}`; });
